#!/usr/bin/env bash
# Concatenates supabase/migrations/*.sql into supabase/ALL_MIGRATIONS.sql so the
# whole schema applies with a single paste into the Supabase SQL editor.
# Run after changing any migration.
set -euo pipefail
cd "$(dirname "$0")/.."
{
  echo "-- ============================================================================"
  echo "-- Kabra Architects dashboard - ALL MIGRATIONS"
  echo "--"
  echo "-- Generated file: migrations 0001-0004 concatenated, in order, so the whole"
  echo "-- schema can be applied with a single paste into the Supabase SQL editor."
  echo "-- Do not edit this file. Edit the numbered migrations and regenerate:"
  echo "--     npm run build:migrations"
  echo "--"
  echo "-- Each migration is its own transaction, so a failure rolls back that file"
  echo "-- only and the error message names which one."
  echo "-- ============================================================================"
  echo
  for f in supabase/migrations/000*.sql; do
    echo ""
    echo "-- ############################################################################"
    echo "-- ## $(basename "$f")"
    echo "-- ############################################################################"
    echo ""
    cat "$f"
  done
} > supabase/ALL_MIGRATIONS.sql
echo "wrote supabase/ALL_MIGRATIONS.sql ($(wc -l < supabase/ALL_MIGRATIONS.sql) lines)"
